-- Supabase schema migration for ingredient parsing support
-- Run this in the Supabase SQL editor or via your database migration process.

-- 1. Add a child table to store parsed recipe ingredients.
CREATE TABLE IF NOT EXISTS public."Recipe_Ingredients" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id bigint NOT NULL REFERENCES public."Recipes"(id) ON DELETE CASCADE,
  raw_text text NOT NULL,
  canonical_text text NOT NULL,
  quantity text,
  unit text,
  quantity_metric text,
  unit_metric text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recipe_ingredients_recipe_id_idx ON public."Recipe_Ingredients" (recipe_id);
CREATE INDEX IF NOT EXISTS recipe_ingredients_canonical_text_idx ON public."Recipe_Ingredients" (canonical_text);

-- 2. Add a parse status marker to the Recipes table.
ALTER TABLE public."Recipes"
  ADD COLUMN IF NOT EXISTS ingredients_parsed boolean NOT NULL DEFAULT false;

-- 3. Optional: add an index for quick menu filtering.
CREATE INDEX IF NOT EXISTS recipes_ingredients_parsed_idx ON public."Recipes" (ingredients_parsed);
